# Creates blurbs for the control-bar-to-persona-bar topic.
# USAGE: powershell -file mkcp2pb.ps1 menus-cp2pb.csv > cp2pb.out
#

function UIControl  {
    param( [string] $s, [string] $type )

    if (( $s -eq "" ) -or ( $s -eq "???" ))  {
        return( "" )
    }
    elseif ( $s.StartsWith( "(" ) )  {
        return( $s.Trim() )
    }
    elseif ( $s.Contains( "<uicontrol>" ) )  {
        return( $s.Trim() )
    }
    else  {
        return( "<uicontrol>" + $s.Trim() + "</uicontrol>" + $type )
    }
}


function PrintMenuPath  {
    param( [string] $menu1, [string] $menu2, [string] $tab1, [string] $tab2, [string] $addinfo, [string] $howto )

    $menu1ui = UIControl $menu1 ""
    $menu2ui = UIControl $menu2 ""
    $tab1ui = UIControl $tab1 " tab"
    $tab2ui = UIControl $tab2 " subtab"

    if ( $menu2 -eq "" )  {
        Write-Host( "                    <stentry>$menu1ui</stentry>" )
    }
    elseif ( $tab1 -eq "" )  {
        Write-Host( "                    <stentry><menucascade>$menu1ui $menu2ui</menucascade></stentry>" )
    }
    else  {
        Write-Host( "                    <stentry>" )
        Write-Host( "                       <ol>" )
        Write-Host( "                           <li><menucascade>$menu1ui $menu2ui</menucascade></li>" )

        Write-Host( "                           <li>$tab1ui</li>" )
        if ( $tab2 -ne "" )  {
            Write-Host( "                           <li>$tab2ui</li>" )
        }

        Write-Host( "                       </ol>" )

        if ( $howto -ne "" )  {
            Write-Host( "                       <p audience=""adm cmg""><xref format=""dita"" href=""$howto"">[how to]</xref></p>" )
        }

        if ( $addinfo -ne "" )  {
            Write-Host( "                       <p>$addinfo</p>" )
        }
        Write-Host( "                    </stentry>" )
    }
}


# MAIN
if ( $args.Count -gt 0 )  {
    $srccsv = $args[0]


    $thisscript = $MyInvocation.MyCommand.Name;
    Write-Host( "" )
    Write-Host( "" )
    Write-Host( "        <!-- ====================================================== -->" )
    Write-Host( "        <!-- This section was generated by running: powershell -file $thisscript $srccsv > cp2pb.out -->" )
    Write-Host( "        <!-- START GENERATED SECTION -->" )

    $cp1curr = ""
    $cp2curr = ""
    $cp3curr = ""

	foreach ( $ln in ( Import-Csv $srccsv ) )  {
        # if menu option line
        if ( $ln.pb1 -ne "" )  {

            # if end of section (cp1)
            if ( $ln.cp1 -ne $cp1curr ) {

                # End the previous table, if any.
                if ( $cp1curr -ne "" )  {
                    Write-Host( "            </simpletable>" )
                    # if going from Common to Advanced, don't start a new section.
                    if ( $cp2curr -ne "Common" )  {
                        Write-Host( "        </section>" )
                    }
                }

                # Header for section

                $cp1tc = $ln.cp1
                $cp1lc = ($ln.cp1).ToLower().Replace( " ", "-" )
                $cp2tc = $ln.cp2

                Write-Host( "" )
                Write-Host( "" )

                # if going from Common to Advanced, don't start a new section.
                if ( $ln.cp2 -ne "Advanced" )  {
                    Write-Host( "        <section id=""section-menu-changes-$cp1lc"">" )
                    Write-Host( "            <title>$cp1tc</title>" )
                    Write-Host( "" )
                }
                else  {
                    Write-Host( "" )
                }

                $cpimage = $ln.cpimage
                if ( $cp2 -eq "Common" -or $cp2 -eq "Advanced" )  {
                    Write-Host( "            <image outputclass=""img-scr-menu"" scalefit=""yes"" placement=""break"" align=""left"" href=""../common/img/$cpimage""><alt>Old Control Panel/Bar menu - $cp1tc &gt; $cp2tc</alt></image>" )
                }
                else  {
                    Write-Host( "            <image outputclass=""img-scr-menu"" scalefit=""yes"" placement=""break"" align=""left"" href=""../common/img/$cpimage""><alt>Old Control Panel/Bar menu - $cp1tc</alt></image>" )
                }

                Write-Host( "            <simpletable relcolwidth=""1* 1*"">" )
                Write-Host( "                <sthead>" )
                Write-Host( "                    <stentry><uicontrol>Control Panel/Bar</uicontrol></stentry>" )
                Write-Host( "                    <stentry><uicontrol>Persona Bar</uicontrol></stentry>" )
                Write-Host( "                </sthead>" )

            }  # if end of section (cp1)


            # Each menu option line in the csv is a row.

            Write-Host( "                <strow>" )

            # Control Panel/Bar
            PrintMenuPath $ln.cp1 $ln.cp3 $ln.cptab1 $ln.cptab2 "" ""

            # Persona Bar
            PrintMenuPath $ln.pb1 $ln.pb2 $ln.pbtab1 $ln.pbtab2 $ln.addinfo $ln.howto

            # Update the curr vars for comparison with the next menu option line.
            $cp1curr = $ln.cp1
            $cp2curr = $ln.cp2
            $cp3curr = $ln.cp3

            Write-Host( "                </strow>" )

        } # if menu option line

    }  # foreach

    Write-Host( "            </simpletable>" )
    Write-Host( "        </section>" )
    Write-Host( "" )
    Write-Host( "        <!-- END GENERATED SECTION -->" )
}