# Creates the boilerplates for the Persona Bar images.
# USAGE: powershell -file mkbp-generic.ps1 generic.csv > mkbp-generic.out
#
# WARNINGS:
#   * For overlays on the image:
#       - Do NOT use "align=". It creates a <div> around the image.
#       - Do NOT use "placement="break"". It adds <br/> before and after the image.


$menusep = "&gt;"
$fnprefix = "pbar-"
$fnsuffix = ".csv"
$asciibase = 64     # 'A' is 65.
$pbicon1 = "&#10122;"
$pbicon2 = "&#10123;"


function MkBlurb  {
    param( [string] $tab, [string] $subtab )

    if ( $tab -ne "" )  {
        $tababbr = "-" + $tab.Replace( " ", "" )
    }
    if ( $subtab -ne "" )  {
        $subtababbr = "-" + $subtab.Replace( " ", "" )
    }

    Write-Host( "" )
    Write-Host( "            <!-- <step conref=""bptext-steps.dita#tsk-bptext-steps/step-pb-SiteSettings$tababbr$subtababbr-E90""><cmd/></step> -->" )
    Write-Host( "            <!-- <step conkeyref=""k-bpsteps/step-pb-SiteSettings$tababbr$subtababbr-E90""><cmd/></step> -->" )
    Write-Host( "            <step id=""step-pb-SiteSettings$tababbr$subtababbr-E90"">" )
    Write-Host( "                <cmd>Go to the <uicontrol>$tab</uicontrol> tab, then the <uicontrol>$subtab</uicontrol> subtab.</cmd>" )
    Write-Host( "                <info><image outputclass=""img-scr"" scalefit=""yes"" placement=""break"" align=""left"" href=""img/scr-SiteSettings$tababbr$subtababbr-E90.png""><alt>Settings &gt; Site Settings &gt; $tab &gt; $subtab</alt></image></info>" )
    Write-Host( "            </step>" )
}


# MAIN
if ( $args.Count -gt 0 )  {
    $srccsv = $args[0]

    $thisscript = $MyInvocation.MyCommand.Name;
    Write-Host( "" )
    Write-Host( "" )
    Write-Host( "        <!-- =================================================== -->" )
    Write-Host( "        <!-- This section was generated by running: powershell -file $thisscript $srccsv > mkbp-generic.out -->" )
    Write-Host( "        <!-- START GENERATED SECTION -->" )

	foreach ( $ln in ( Import-Csv $srccsv ) )  {
        $tab = $ln.tab
        $subtab = $ln.subtab
        MkBlurb $tab $subtab
    }

    Write-Host( "" )
    Write-Host( "        <!-- END GENERATED SECTION -->" )
    Write-Host( "        <!-- =================================================== -->" )
}
