# ============================================================
# Builds the DocCenter html files using DITA-OT.
#
# Prerequisites (You only have to do these once, not per build.):
# 1. Install Java SE JDK.
#      http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
# 2. Download and extract DITA-OT to %DITA_HOME%.
#      http://www.dita-ot.org/download
# ============================================================

$dropbox = "C:\Users\eleanor.tesoro\Dropbox (DNN Corp)\DocCenter - originals\_archives\DC1.3 archive"
$localhostdir = "c:\inetpub\wwwroot\docs"

$subbldarr = "administrators", "developers", "designers", "content-managers", "community-managers"
$transtype = "html5"
$bldroot   = "v:"
$gitroot   = "w:"
$ditahome  = "C:\dita-ot"

$blddir = $bldroot + "\bld\" + $transtype
$gitdir = $gitroot + "\."
$thmdir = $gitroot + "\_themes\dnn"
$outdir = $bldroot + "\output\" + $transtype
$zipdir = $bldroot + "\output\"
$logdir = $bldroot + "\logs"
$bldlog = $logdir + "\bld-" + $transtype + ".log"
$cpylog = $logdir + "\cpy-" + $transtype + ".log"

$ditaotver = "2.2.2"
$ditaotzip = $gitroot + "\_build\dita-ot-$ditaotver.zip"

$javajdkver = "jdk1.8.0_121"
$javahome  = $env:ProgramFiles + "\Java\" + $javajdkver

$thmdir  = $gitroot + "\_themes\dnn"
$cssfile = $thmdir + "\dnndocsltr.css"

$cssjsarr = ( "dnndocsltr.css", "headscripts.js", "scripts.js" )

# _outext is the file extension of the web pages generated by the build. Can also be .shtml.
# If you change _outext, remember to replace the links in the root index.html.
$outext = ".html"


function Usage()  {
    $script = $MyInvocation.ScriptName
    $usage = "powershell -file $script "
    $examples = @(
        "powershell -file $script _publicclasses.txt "
        )

    Write-Host "Usage: " $usage
    Write-Host "Examples: "
    $examples | foreach { Write-Host "    " $_ }
}


function Pause()  {
    Write-Host "Press any key to continue ..."
    $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyUp") | Out-Null
}


# This is a hack because of issues with figuring out Powershell escape characters and parameters in strings.
function RunBat( [string] $exeandparams )  {
    $tempbat = $blddir + "\temp.bat"
    New-Item $tempbat  -Type file  -Force  -Value $exeandparams | Out-Null
    & "cmd.exe" /c $tempbat
}


# Gets the original drive of a mapped drive.
function GetRemoteDrive( [string] $mapdrv )  {
    $mapdrv = $mapdrv.ToUpper()
    $logicalDisk = Get-WMIObject Win32_LogicalDisk -filter "DriveType = 4 AND DeviceID = '$mapdrv'"
    return ( $logicalDisk.ProviderName )
}


# Gets the line in the resource file (js|css) that contains the parameters to add to the URL calling the resource.
function GetVersionURLParams( [string] $fn )  {
    $prefixsearch = " | ?ver="
    $prefixtrim   = " | "
    Get-Content $fn | Where { $_.StartsWith( $prefixsearch ) } | foreach  {
        $x = $_.Replace( $prefixtrim, "" )
        return ( $x )
    }
}


function SetBldEvars()  {
    Write-Host "Setting environment variables ...."

    if ( $env:_gitdir  -eq $NULL )  { $env:_gitdir  = $gitdir }  else { $gitdir  = $env:_gitdir  }
    if ( $env:_blddir  -eq $NULL )  { $env:_blddir  = $blddir }  else { $blddir  = $env:_blddir  }
    if ( $env:_outdir  -eq $NULL )  { $env:_outdir  = $outdir }  else { $outdir  = $env:_outdir  }
    if ( $env:_logdir  -eq $NULL )  { $env:_logdir  = $logdir }  else { $logdir  = $env:_logdir  }
    if ( $env:_logfile -eq $NULL )  { $env:_logfile = $bldlog }  else { $bldlog  = $env:_logfile }

    $env:_outext = $outext

    if ( $env:DITA_HOME -eq $NULL )  { $env:DITA_HOME = $ditahome }  else { $ditahome = $env:DITA_HOME }
    if ( $env:ANT_HOME  -eq $NULL )  { $env:ANT_HOME  = $ditahome }  else { $anthome = $env:DITA_HOME  }
    $antexe  = $anthome + "\bin\ant.bat"

    if ( $env:JAVA_HOME -eq $NULL )  { $env:JAVA_HOME = $javahome }  else { $javahome = $env:JAVA_HOME }
    $javaexe = $javahome + "\bin\java.exe"
    if ( Test-Path $javaexe )     { $env:JAVACMD = $javaexe    }  else { $env:JAVACMD = "java.exe"  }

    $env:PATH = $javahome + "\bin;" + $ditahome + "\bin;" + $anthome + "\tools\ant\bin;" + $env:PATH

    # from $ditahome\resources\env.bat
    $addclasspath = "$ditahome\plugins\org.dita.pdf2\lib\fo.jar;$ditahome\plugins\org.dita.pdf2.axf\lib\axf.jar;$ditahome\plugins\org.dita.pdf2.xep\lib\xep.jar"
    if ( $env:_logfile -eq $NULL )  {
        $env:CLASSPATH = $addclasspath
    }
    else  {
        $env:CLASSPATH = $env:CLASSPATH + ";" + $addclasspath
    }

    Write-Host "    gitdir:   $gitdir  "
    Write-Host "    blddir:   $blddir  "
    Write-Host "    outdir:   $outdir  "
    Write-Host "    logdir:   $logdir  "
    Write-Host "    logfile:  $bldlog  "
    Write-Host "    ditahome: $ditahome"
    Write-Host "    anthome:  $anthome "
    Write-Host "    antexe:   $antexe  "
    Write-Host "    javahome: $javahome"
    Write-Host "    CLASSPATH: $env:CLASSPATH"
}


function ChkThenMkDir( [string] $folder )  {
    if ( -not( Test-Path $folder ) )  {
        New-Item  $folder  -Type directory | Out-Null
    }
}

function ChkThenRmDir( [string] $folder )  {
    if ( Test-Path -Path $folder )  {
        Remove-Item $folder -Recurse -Force | Out-Null
    }

    $confirmation = 'r'
    while (( Test-Path -Path $folder ) -and ( $confirmation -eq 'r' ))  {
        $confirmation = Read-Host "Unable to clear $_. Proceed anyway [p], retry [r], or cancel [x]?"
        switch ( $confirmation ) {
            'r' { Remove-Item $folder -Recurse -Force | Out-Null }
            'x' { throw "Cancelled by user." }
        }
    }
}


# $opts: /s = subdirectories
function RobocopyBasic( [string] $src, [string] $tgt, [string] $opts )  {
    Write-Host "Copying from $src to $tgt with options $opts ...."
    $cmd = "@robocopy " + $src + " " + $tgt + " /mt /log+:" + $cpylog + " " + $opts
    RunBat $cmd | Out-Null
}
function RobocopyIncludeArray( [string] $src, [string] $tgt, [string] $includearr, [string] $opts )  {
    Write-Host "Copying from $src to $tgt, including $includearr, with options $opts ...."
    $includearr.Split( "," ) | foreach  {
        $cmd = "@robocopy " + $src + " " + $tgt + " " + $_ + " /mt /log+:" + $cpylog + " " + $opts
        RunBat $cmd | Out-Null
    }
}
function RobocopyExcludeFiles( [string] $src, [string] $tgt, [string] $excludefiles, [string] $opts )  {
    Write-Host "Copying from $src to $tgt, excluding $excludefiles, with options $opts ...."
    $cmd = "@robocopy " + $src + " " + $tgt + " /xf " + $excludefiles + " /mt /log+:" + $cpylog + " " + $opts
    RunBat $cmd | Out-Null
}
function RobocopyExcludeDirs( [string] $src, [string] $tgt, [string] $excludedirs, [string] $opts )  {
    Write-Host "Copying from $src to $tgt, excluding $excludedirs, with options $opts ...."
    $cmd = "@robocopy " + $src + " " + $tgt + " /xd " + $excludedirs + " /mt /log+:" + $cpylog + " " + $opts
    RunBat $cmd | Out-Null
}


function RefreshLog()  {
    Write-Host "Recreating $logfile ...."

    if ( -not( Test-Path -Path $logdir ) )  {
        New-Item  $logdir  -Type directory  -Force | Out-Null
    }

    ( $bldlog, $cpylog ) | foreach  {
        if ( Test-Path -Path $_ )  {
            Remove-Item  $_  -Force  | Out-Null
        }
        New-Item  $_  -Type file  -Force | Out-Null
    }
}


function RefreshFolders()  {
    Write-Host "Recreating build folder and output folder ...."

    $fails = 0
    ( $blddir, $outdir ) | foreach {
        ChkThenRmDir $_
        if ( -not( Test-Path -Path $_ ) )  {
            New-Item $_  -Type directory  -Force | Out-Null
        }
    }
}


function RefreshDITAOT()  {
    Write-Host "Refreshing the DITA-OT files ...."

    if ( Test-Path $ditahome )  {
        Remove-Item $ditahome -Recurse -Force
    }

    $zipexe = $env:ProgramFiles + "\7-Zip\7z.exe"
    $tgtdir = $ditahome + "\.."
    $params = "-o" + $tgtdir
    & "$zipexe" x $params $ditaotzip
    $arr = Get-ChildItem $tgtdir\dita-ot-*
    Rename-Item $arr[0] $ditahome

    if ( $ditaotver -eq "2.4.2" )  {
        # Hack while waiting for official fix: https://github.com/dita-ot/dita-ot/pull/2574
        Copy-Item -Path $gitroot\_build\org.dnn.dc\xsl\dnn-topic.xsl -Destination $ditahome\plugins\org.dita.html5\xsl\topic.xsl -Force
    }

    # DNN-specific files.
    ( "$ditahome\plugins\org.dnn.dc" ) | foreach  {
        ChkThenRmDir $_
        if ( -not( Test-Path -Path $_ ) )  {
            New-Item $_  -Type directory  -Force | Out-Null
            RobocopyBasic "$gitdir\_build\org.dnn.dc" $_ "/s"
        }
    }

    Write-Host "Integrating our own DITA-OT plugin ...."
    Set-Location  -Path $ditahome
    RunBat "ant -f integrator.xml  strict"
}


# Returns $TRUE if the current date meets the condition.
# $cond can be "PRE" to check if the current date is before $yyyyMMdd.
# $cond can be "POST" to check if the current date is before $yyyyMMdd.
function isActiveDate( [string] $cond, [string] $yyyyMMdd )  {
    $now = Get-Date -Format "yyyyMMdd"
    switch ( $cond ) {
        "PRE"  { return { $now -lt $yyyyMMdd } }
        "POST" { return { $now -gt $yyyyMMdd } }
    }
}
# Copies time-sensitive versions of files in the build folder.
# The temporary version of the file must be named as follows:
#   PRE_YYYYMMDD_original-filename.dita  - The temporary file will be used before the specified date.
#   POST_YYYYMMDD_original-filename.dita - The temporary file will be used after the specified date.
function CopyTimeSensitiveFiles( [string] $src, [string] $tgt, [string] $filter )  {
    Write-Host "Copying time-sensitive versions ...."

    foreach ( $prefix in @( "PRE", "POST" ) )  {
        $inc = $prefix + "_*" + $filter
        Get-ChildItem -Path $src\.. -Include $inc -Recurse | foreach {
            $fnarr = ($_.Name).Split( "_", [System.StringSplitOptions]::RemoveEmptyEntries )
            if ( isActiveDate $prefix $fnarr[1] ) {
                $fn = $_.FullName
                $path = $_.DirectoryName
                if ( $tgt -ne $NULL )  {
                    $path.Replace( $src, $tgt )
                }
                $cleanfn = $fnarr[2]
                Copy-Item  -Path $fn -Destination "$path\$cleanfn" -Force
            }
        }
    }
}


# This is a hack because the css references require changes in the DITA-OT XSLT.
# The js references are easy to update in dnn-head and dnn-footer, but added here anyway for consistency.
function AddVersioning( [string] $tgtdir, [string] $fnfilter )  {
    Write-Host "Adding versioning for .css and .js in $tgtdir\$fnfilter ...."

    $rep1 = GetVersionURLParams "$thmdir\dnndocsltr.css"
    $rep2 = GetVersionURLParams "$thmdir\headscripts.js"
    $rep3 = GetVersionURLParams "$thmdir\scripts.js"

    # Retrieve every file that meets the $fnfilter.
    $arr  = Get-ChildItem -Path $tgtdir   -Include $fnfilter -Recurse

    Write-Host "dnndocsltr.css$rep1"
    Write-Host "headscripts.js$rep2"
    Write-Host "scripts.js$rep3"
    Write-Host "Updating " $arr.Length " files ...."
    foreach ( $fn in $arr )  {
        ( Get-Content $fn ) | foreach  {
            $_  -replace "/dnndocsltr.css", "/dnndocsltr.css$rep1"`
                -replace "/headscripts.js", "/headscripts.js$rep2"`
                -replace "/scripts.js"    , "/scripts.js$rep3"
        } | Set-Content $fn
    }
}


function CopyBldFolders()  {
    Write-Host "Copying files required by the build ...."

    Write-Host "Copying from $gitdir\_content to $blddir"
    RobocopyIncludeArray  "$gitdir\_content"                 "$blddir"                 "*.dita*,*.png,*.gif,*.svg" "/s"
    RobocopyBasic         "$gitdir\_content\common\samples"  "$blddir\common\samples"                              "/s"
    RobocopyIncludeArray  "$gitdir\_themes\dnn"              "$blddir\_themes\dnn"     "dnn*.css"

    CopyTimeSensitiveFiles $blddir $blddir

    foreach ( $subbld in $subbldarr )  {
        RobocopyIncludeArray "$blddir\common" "$blddir\$subbld" "*.dita*" "/s"
    }
}


function BuildDITADocs()  {
    Write-Host "Building ...."

    Copy-Item  -Path $gitdir\_build\dnn_build.xml  -Destination $ditahome  -Force | Out-Null
    Copy-Item  -Path $gitdir\_build\*.ditaval      -Destination $ditahome  -Force | Out-Null

    # Must start at $ditahome
    Set-Location -Path $ditahome
    $batcontents = "ant " + $transtype + " -f " + $ditahome + "\dnn_build.xml -l " + $bldlog
    RunBat $batcontents
}


function AssembleOutput()  {
    Write-Host "Copying additional required files to the output ...."

    Copy-Item  -Path "$gitdir\_content\index.html"          -Destination "$outdir"  -Force | Out-Null
    CopyTimeSensitiveFiles "$gitdir\_content" $outdir "index.html"

    Copy-Item  -Path "$gitdir\_content\searchresults.html"  -Destination "$outdir"  -Force | Out-Null
    CopyTimeSensitiveFiles "$gitdir\_content" $outdir "searchresults.html"

    RobocopyBasic         "$gitdir\_content\common\samples"   "$outdir\common\samples"                                          "/s"
    # RobocopyBasic         "$gitdir\_content\ssi"              "$outdir\ssi"                                                     "/s"
    RobocopyIncludeArray  "$gitdir\_content\common\img"       "$outdir\common\img"      "*.jpg,*.png,*.gif,*.svg"
    RobocopyIncludeArray  "$gitdir\_themes\dnn"               "$outdir\_theme"          "*.jpg,*.png,*.gif,*.svg,26d3f6*,*.js"

    # The following is a hack.
    Copy-Item  -Path $outdir\developers\creating-modules\index.html  -Destination $outdir\developers\extensions  -Force
    Copy-Item  -Path $outdir\designers\creating-themes\index.html    -Destination $outdir\designers\extensions   -Force

    Write-Host "Deleting files we don't need ...."
    if ( Test-Path $outdir\toc.html          )  { Remove-Item $outdir\toc.html -Force | Out-Null }
    if ( Test-Path $outdir\common\glossary\* )  { Remove-Item $outdir\common\glossary -Recurse -Force | Out-Null }

    # Write-Host "Adding versioning to .css and .js calls in html files ...."
    AddVersioning $outdir "*.html"

    Write-Host "Creating the web.config ...."
    & $gitdir\_build\urlmap\urlmap.ps1 $gitdir\_build\urlmap\DC-URLmapping.csv $outdir $outdir\web.config

    Write-Host "Creating an aboutbld.html file ...."
    $today = Get-Date  -Format "yyyyMMdd"
    Write-Output "DocCenter v1.3 Build $today" | Set-Content $outdir\aboutbld.html
}


function Publish2Localhost()  {

    # Replace the mapped build drive with the WMI ProviderName.
    $remotedrv = GetRemoteDrive( $bldroot )
    if ( $remotedrv )  {
        $srcdir = $outdir.Replace( $bldroot, $remotedrv )
    }
    else  {
        $srcdir = $outdir
    }
    Explorer $srcdir
    Explorer $localhostdir

    <#
    Write-Host "Copying built files from $srcdir to $localhostdocdir ...."
    Remove-Item $localhostdocdir -Recurse -Force
    New-Item $localhostdocdir  -Type directory  -Force
    Copy-Item  -Path $remoteblddir\_content\web.config  -Destination $outdir  -Recurse  -Force
    #>
}


function ZipOutput()  {
    $now = Get-Date -Format "yyyyMMddHHmm"
    $tgtzip = "$zipdir\$now-$transtype.zip"

    Write-Host "Zipping to $tgtzip...."
    if ( Test-Path $tgtzip )  { Remove-Item $tgtzip -Force }
    Compress-Archive  -Path $outdir  -DestinationPath $tgtzip
    Copy-Item  -Path $tgtzip  -Destination $dropbox  -Force
}


# MAIN -------------------------------------------------------

    $stopwatch = New-Object -TypeName System.Diagnostics.Stopwatch
    $stopwatch.Start

    SetBldEvars
    RefreshLog
    RefreshFolders
    RefreshDITAOT
    CopyBldFolders
    BuildDITADocs

    $failed = 0
    $subbldarr | foreach  {
        if ( -not( Test-Path -Path $outdir\$_\* ) )  {
            Write-Host "FATAL: Build failed for the subcenter $_."
            $failed += 1
        }
    }
    if ( $failed -gt 0 )  {
        & "cmd.exe" /c npp.bat $bldlog
    }
    else  {
        AssembleOutput
        Publish2Localhost
        ZipOutput
    }

    Write-Host $stopwatch.Elapsed.ToString()
    $stopwatch.Stop


# ============================================================

# TODO: Display error/warn lines in the %_logfile%.
# TODO: Copy to staging server via Filezilla.
    # echo Copy the following to the Windows Explorer address bar: ftp://66.29.195.16/DNN%20Staging/DNNSoftware.QA.Docs/
    # echo In Filezilla, use the following:
    # echo    Host: 66.29.195.16
    # echo    Port: 25
    # echo Use your username and password from Birch.
    # call "C:\Program Files\FileZilla FTP Client\filezilla.exe"

# ============================================================
